SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS scenario_assertion_results;
DROP TABLE IF EXISTS scenario_step_runs;
DROP TABLE IF EXISTS scenario_runs;
DROP TABLE IF EXISTS connectors;
DROP TABLE IF EXISTS environments;
DROP TABLE IF EXISTS scenario_candidates;
DROP TABLE IF EXISTS scenario_steps;
ALTER TABLE scenarios DROP FOREIGN KEY fk_scenarios_current_version;
DROP TABLE IF EXISTS scenario_versions;
DROP TABLE IF EXISTS scenarios;
DROP TABLE IF EXISTS scenario_imports;
DROP TABLE IF EXISTS scenario_discoveries;
DROP TABLE IF EXISTS api_operations;
DROP TABLE IF EXISTS scan_runs;
DROP TABLE IF EXISTS code_sources;
DROP TABLE IF EXISTS system_members;
DROP TABLE IF EXISTS business_systems;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS = 1;
